export const configuration = () => ({
  environment: process.env["NODE_ENV"],
  apiHost: process.env["API_HOST"] || "127.0.0.1",
  apiPort: parseInt(process.env["API_PORT"] || "3000", 10),
  limit: parseInt(process.env["LIMIT"] || "15", 10),
  openAiKey: process.env["OPENAI_KEY"],
  dbHost: process.env["DB_HOST"] || "127.0.0.1",
  dbPort: parseInt(process.env["DB_PORT"] || "5432", 10),
  dbUser: process.env["DB_USER"] || "mysql",
  dbPassword: process.env["DB_PASSWORD"] || "",
  dbName: process.env["DB_NAME"] || "workforce",
  smtpHost: process.env["SMTP_HOST"] || "127.0.0.1",
  smtpPort: parseInt(process.env["SMTP_PORT"] || "587", 10),
  smtpUser: process.env["SMTP_USER"] || "",
  smtpPassword: process.env["SMTP_PASSWORD"] || "",
  smtpSecure: process.env["SMTP_SECURE"] === "true",
  mailTemplatePath: process.env["MAIL_TEMPLATE_PATH"] || "",
  jwtPrivateKey: process.env["JWT_PRIVATE_KEY"],
  jwtPublicKey: process.env["JWT_PUBLIC_KEY"],
  identifier: process.env["PURCHASE_IDENTIFIER"],
  jwtExpiry: process.env["JWT_EXPIRY"],
  jwtRefreshExpiry: process.env["JWT_REFRESH_EXPIRY"],
  jwtIssuer: process.env["JWT_ISSUER"],
  jwtAlgorithm: process.env["JWT_ALGORITHM"] || "RS256",
  storageType: process.env["STORAGE_TYPE"] || "DISK",
  uploadPath: process.env["UPLOAD_PATH"] || "",
  logType: process.env["LOG_TYPE"] || "console",
  logFileNameFormat: process.env["LOG_FILE_NAME_FORMAT"] || "YYYY-MM-DD",
  logPath: process.env["LOG_PATH"],
  logLevel: process.env["LOG_LEVEL"] || "DEBUG",
  googleClientId: process.env["GOOGLE_CLIENT_ID"] || "",
  googleClientSecret: process.env["GOOGLE_CLIENT_SECRET"] || "",
  googleRedirectUrl: process.env["GOOGLE_REDIRECT_URL"] || "",
  twitterAPIKey: process.env["TWITTER_API_KEY"] || "",
  twitterAPIKeySecret: process.env["TWITTER_API_KEY_SECRET"] || "",
  twitterRedirectUrl: process.env["TWITTER_REDIRECT_URL"] || "",
  msClientId: process.env["MS_CLIENT_ID"] || "",
  msObjectId: process.env["MS_OBJECT_ID"] || "",
  msTanentId: process.env["MS_TENANT_ID"] || "",
  msSecretValue: process.env["MS_SECRET_VALUE"] || "",
  msRedirectUrl: process.env["MS_REDIRECT_URL"] || "",
  appleClientId: process.env["APPLE_CLIENT_ID"] || "",
  appleTeamId: process.env["APPLE_TEAM_ID"] || "",
  appleKeyId: process.env["APPLE_KEY_ID"] || "",
  appleKeyPath: process.env["APPLE_KEY_PATH"] || "",
  appleRedirectUrl: process.env["APPLE_REDIRECT_URL"] || "",
  appleBundleId: process.env["APPLE_BUNDLE_ID"] || "",
  sendgridApiKey: process.env["SENDGRID_API_KEY"] || "",
  mailSource: process.env["MAIL_SOURCE"] || "",
  enableLogger: process.env["ENABLE_LOGGER"] || "",
});
