export enum ActivityType {
  USER = 'USER',
  CATEGORY = 'CATEGORY',
  MEDIA = 'MEDIA',
  NEWSLETTER = 'NEWSLETTER',
  ROLE = 'ROLE',
  STORY = 'STORY',
  PUBLICATION = 'PUBLICATION',
  AUTH = 'AUTH',
  TEAM = 'TEAM',
}
